package de.oszimt.DreiSchichten.view;

import de.oszimt.DreiSchichten.controller.ViewController;
import de.oszimt.DreiSchichten.model.Beruf;
import de.oszimt.DreiSchichten.model.Berufstyp;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Konstantin Görlitz
 */
public class Berufsliste extends javax.swing.JPanel {

    private ViewController viewcontroller;
    private int mitgliedid;
    private List<Beruf> berufsliste;
    
    /**
     * Creates new form Berufsliste
     */
    public Berufsliste() {
        initComponents();
        fillCombobox();
    }
    
    private void fillCombobox(){
        for(Berufstyp berufstyp : viewcontroller.getBerufstypen()){
            jcBeruf.addItem(berufstyp);
        }
    }
    
    public Berufsliste(List<Beruf> berufe){
        this();
        setInhalte(berufe);
        this.berufsliste=berufe;
    }
    
    public void setInhalte(List<Beruf> berufe){
        DefaultTableModel model = (DefaultTableModel)jtBerufliste.getModel();
        model.setRowCount(0);
        for(final Beruf beruf : berufe){
            JButton button1 = new JButton("L");
            button1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    löscheBeruf(beruf.getId());
                }
            });
            
            
            Object[] row = {beruf.getId(), viewcontroller.getBerufName(beruf.getTypID()), beruf.getPunkte(),
                button1};
            model.addRow(row);
            
        }
    }
    
    public Berufsliste(List<Beruf> berufe, ViewController vc){
        this(berufe);
        this.viewcontroller=vc;
    }
    
    private Beruf findeBeruf(int berufid){
        for(Beruf beruf : this.berufsliste){
            if(beruf.getId()==berufid){
                return beruf;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitel = new javax.swing.JLabel();
        jlBeruf = new javax.swing.JLabel();
        jcBeruf = new javax.swing.JComboBox();
        jlPunkte = new javax.swing.JLabel();
        jtPunkte = new javax.swing.JTextField();
        jbAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBerufliste = new javax.swing.JTable();

        jlTitel.setText("Berufsliste");

        jlBeruf.setText("Beruf");

        jlPunkte.setText("Punkte");

        jtPunkte.setToolTipText("");
        jtPunkte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPunkteActionPerformed(evt);
            }
        });

        jbAdd.setText("Add");
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jtBerufliste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Beruf ID", "Beruf", "Punkte", "Löschen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtBerufliste);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBeruf)
                            .addComponent(jcBeruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtPunkte, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbAdd))
                            .addComponent(jlPunkte)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBeruf)
                    .addComponent(jlPunkte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPunkte, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcBeruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void löscheBeruf(int id){
        viewcontroller.deleteBeruf(id);
        jtBerufliste.remove(jtBerufliste.getSelectedRow());
    }
    
    private void jtPunkteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPunkteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPunkteActionPerformed

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        boolean temp=true;
        Berufstyp selectedBeruf = (Berufstyp)jcBeruf.getSelectedItem();
        for(int i=1; i<jtBerufliste.getRowCount(); i++){
            if(selectedBeruf.getName().equals(jtBerufliste.getModel().getValueAt(2, i))){
                jtBerufliste.getModel().setValueAt((Integer.parseInt(jtBerufliste.getModel().getValueAt(2, i).toString())+Integer.parseInt(jtPunkte.getText())), i, 3);
                temp=false;
                Beruf b = findeBeruf(Integer.parseInt(jtBerufliste.getValueAt(i, 1).toString()));
                b.setPunkte(Integer.parseInt(jtBerufliste.getValueAt(i, 3).toString()));
                viewcontroller.updateBeruf(b);
            }
            
        }
        if(temp){
            Beruf newBeruf = new Beruf();
            newBeruf.setTypID(selectedBeruf.getId());
            newBeruf.setMitgliedID(mitgliedid);
            newBeruf.setPunkte(Integer.parseInt(jtPunkte.getText()));
            viewcontroller.addBeruf(newBeruf);
            setInhalte(viewcontroller.getBerufe(mitgliedid));
        }
    }//GEN-LAST:event_jbAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdd;
    private javax.swing.JComboBox jcBeruf;
    private javax.swing.JLabel jlBeruf;
    private javax.swing.JLabel jlPunkte;
    private javax.swing.JLabel jlTitel;
    private javax.swing.JTable jtBerufliste;
    private javax.swing.JTextField jtPunkte;
    // End of variables declaration//GEN-END:variables
}
