/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.oszimt.DreiSchichten.view;

import de.oszimt.DreiSchichten.controller.ViewController;
import de.oszimt.DreiSchichten.model.Dorf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Konstantin Görlitz
 */
public class Dorfliste extends javax.swing.JPanel {
    
    private ViewController viewcontroller;

    /**
     * Creates new form Dörfer
     */
    public Dorfliste() {
        initComponents();
    }
    
    public Dorfliste(List<Dorf> dorfliste){
        this();
        setDörfer(dorfliste);
    }
    
    public void setDörfer(List<Dorf> dorfliste){
        DefaultTableModel model = (DefaultTableModel)jtDorfliste.getModel();
        for(final Dorf dorf : dorfliste){
            JButton button1 = new JButton("B");
            button1.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    bearbeiteDorf(dorf.getId());
                }
            });
            
            JButton button2 = new JButton("E");
            button2.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    öffneEinwohner(dorf.getId());
                }
            });
            
            JButton button3 = new JButton("L");
            button3.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    löscheDorf(dorf.getId());
                }
            });
            
            Object[] row = {dorf.getId(), dorf.getName(), dorf.getMitgliederIDs().length, dorf.getLagerIDs().length, 
                button1, button2, button3};
            model.addRow(row);
            
        }
    }
    
    public Dorfliste(List<Dorf> dorfliste, ViewController vc){
        this(dorfliste);
        this.viewcontroller=vc;
    }
    
    private void bearbeiteDorf(int id){
        viewcontroller.changePanel("BearbeiteDorf", id);
    }
    
    private void öffneEinwohner(int id){
        viewcontroller.changePanel("Mitgliederliste", id);
    }
    
    private void löscheDorf(int id){
        this.viewcontroller.deleteDorf(id);
        jtDorfliste.remove(jtDorfliste.getSelectedRow());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitel = new javax.swing.JLabel();
        jbNeuesDorf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDorfliste = new javax.swing.JTable();
        jbZurück = new javax.swing.JButton();

        jlTitel.setText("Dorfliste");

        jbNeuesDorf.setText("Neues Dorf");
        jbNeuesDorf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNeuesDorfActionPerformed(evt);
            }
        });

        jtDorfliste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Bevölkerung", "Lageranzahl", "Bearbeiten", "Einwohner", "Löschen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtDorfliste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDorflisteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtDorfliste);

        jbZurück.setText("Zurück");
        jbZurück.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbZurückActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTitel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNeuesDorf))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbZurück)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitel)
                    .addComponent(jbNeuesDorf))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbZurück)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbNeuesDorfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNeuesDorfActionPerformed
        viewcontroller.changePanel("NeuesDorf", 0);
    }//GEN-LAST:event_jbNeuesDorfActionPerformed

    private void jtDorflisteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDorflisteMouseClicked
        if(jtDorfliste.getSelectedRow()>0){
            jtDorfliste.getModel().getValueAt(jtDorfliste.getSelectedRow(), 1);
            viewcontroller.changePanel("Lagerliste", Integer.parseInt(jtDorfliste.getModel().getValueAt(jtDorfliste.getSelectedRow(), 1).toString()));
        }
    }//GEN-LAST:event_jtDorflisteMouseClicked

    private void jbZurückActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbZurückActionPerformed
        viewcontroller.changePanel("LastPanel", 0);
    }//GEN-LAST:event_jbZurückActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbNeuesDorf;
    private javax.swing.JButton jbZurück;
    private javax.swing.JLabel jlTitel;
    private javax.swing.JTable jtDorfliste;
    // End of variables declaration//GEN-END:variables
}
