package de.oszimt.DreiSchichten.view;

import de.oszimt.DreiSchichten.controller.DBAccess;
import de.oszimt.DreiSchichten.controller.ViewController;
import de.oszimt.DreiSchichten.model.Lager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Konstantin Görlitz
 */
public class Lagerliste extends javax.swing.JPanel {
    private ViewController viewcontroller;

    /**
     * Creates new form Lagerliste
     */
    public Lagerliste() {
        initComponents();
    }
    
    public Lagerliste(List<Lager> lagerliste){
        this();
        setDörfer(lagerliste);
    }
    
    public void setDörfer(List<Lager> lagerliste){
        DefaultTableModel model = (DefaultTableModel)jtLagerliste.getModel();
        for(final Lager lager : lagerliste){
            JButton button1 = new JButton("B");
            button1.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    öffneLager(lager.getId());
                }
            });
            
            JButton button2 = new JButton("L");
            button2.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    löscheLager(lager.getId());
                }
            });
            
            Object[] row = {lager.getName(), new DBAccess().getRessourceCount() ,
                button1, button2};
            model.addRow(row);
            
        }
    }
    
    public Lagerliste(List<Lager> lagerliste, ViewController vc){
        this(lagerliste);
        this.viewcontroller=vc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitel = new javax.swing.JLabel();
        jbNeuesLager = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLagerliste = new javax.swing.JTable();

        jlTitel.setText("Lagerliste");

        jbNeuesLager.setText("Neues Lager");
        jbNeuesLager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNeuesLagerActionPerformed(evt);
            }
        });

        jtLagerliste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lager", "Inhalt", "Bearbeiten", "Löschen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtLagerliste);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTitel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNeuesLager))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitel)
                    .addComponent(jbNeuesLager))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbNeuesLagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNeuesLagerActionPerformed
        viewcontroller.changePanel("NeuesLager", 0);
    }//GEN-LAST:event_jbNeuesLagerActionPerformed

    private void öffneLager(int id){
        this.viewcontroller.changePanel("Lagerliste", id);
    }
    
    private void löscheLager(int id){
        this.viewcontroller.deleteLager(id);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbNeuesLager;
    private javax.swing.JLabel jlTitel;
    private javax.swing.JTable jtLagerliste;
    // End of variables declaration//GEN-END:variables
}
