package de.oszimt.DreiSchichten.view;

import de.oszimt.DreiSchichten.controller.ViewController;
import de.oszimt.DreiSchichten.model.LagerBestand;
import de.oszimt.DreiSchichten.model.Ressource;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Konstantin Görlitz
 */
public class Lagerinhalt extends javax.swing.JPanel {

    private ViewController viewcontroller;
    private int lagerid;
    
    /**
     * Creates new form Lagerinhalt
     */
    public Lagerinhalt() {
        initComponents();
        fillCombobox();
    }
    
    private void fillCombobox(){
        for(Ressource ressource : viewcontroller.getRessourcen()){
            jcResource.addItem(ressource);
        }
    }
    
    public Lagerinhalt(LagerBestand[] lagerbestände){
        this();
        setInhalte(lagerbestände);
        this.lagerid=lagerbestände[0].getId();
    }
    
    public void setInhalte(LagerBestand[] lagerbestände){
        DefaultTableModel model = (DefaultTableModel)jtLagerinhalt.getModel();
        model.setRowCount(0);
        for(final LagerBestand lagerbestand : lagerbestände){
            JButton button1 = new JButton("L");
            button1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    löscheLagerbestand(lagerbestand.getId());
                }
            });
            
            
            Object[] row = {viewcontroller.getRessourceName(lagerbestand.getId()), lagerbestand.getMenge(),
                button1};
            model.addRow(row);
            
        }
    }
    
    public Lagerinhalt(LagerBestand[] lagerbestände, ViewController vc){
        this(lagerbestände);
        this.viewcontroller=vc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitel = new javax.swing.JLabel();
        jlResource = new javax.swing.JLabel();
        jcResource = new javax.swing.JComboBox();
        jlMenge = new javax.swing.JLabel();
        jtMenge = new javax.swing.JTextField();
        jbAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLagerinhalt = new javax.swing.JTable();

        jlTitel.setText("Lagerinhalt");

        jlResource.setText("Resource");

        jlMenge.setText("Menge");

        jtMenge.setToolTipText("");
        jtMenge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMengeActionPerformed(evt);
            }
        });

        jbAdd.setText("Add");
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jtLagerinhalt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resource", "Menge", "Löschen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtLagerinhalt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlResource)
                            .addComponent(jcResource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtMenge, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbAdd))
                            .addComponent(jlMenge)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlResource)
                    .addComponent(jlMenge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcResource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdd)
                    .addComponent(jtMenge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void löscheLagerbestand(int id){
        viewcontroller.deleteLagerbestand(id);
        jtLagerinhalt.remove(jtLagerinhalt.getSelectedRow());
    }
    
    private void jtMengeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMengeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMengeActionPerformed

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        boolean temp=true;
        Ressource selectedRessource = (Ressource)jcResource.getSelectedItem();
        for(int i=0; i<jtLagerinhalt.getRowCount(); i++){
            if(selectedRessource.getName().equals(jtLagerinhalt.getModel().getValueAt(0, i))){
                jtLagerinhalt.getModel().setValueAt((Integer.parseInt(jtLagerinhalt.getModel().getValueAt(1, i).toString())+Integer.parseInt(jtMenge.getText())), i, 1);
                temp=false;
                viewcontroller.updateLagerbestand(this.lagerid, jtLagerinhalt.getModel().getValueAt(0, i).toString(), Integer.parseInt(jtLagerinhalt.getModel().getValueAt(1, i).toString())+Integer.parseInt(jtMenge.getText()));
            }
            
        }
        if(temp){
            DefaultTableModel model = (DefaultTableModel)jtLagerinhalt.getModel();
            setInhalte(viewcontroller.getLagerbestand(lagerid));
        }
    }//GEN-LAST:event_jbAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdd;
    private javax.swing.JComboBox jcResource;
    private javax.swing.JLabel jlMenge;
    private javax.swing.JLabel jlResource;
    private javax.swing.JLabel jlTitel;
    private javax.swing.JTable jtLagerinhalt;
    private javax.swing.JTextField jtMenge;
    // End of variables declaration//GEN-END:variables
}
