package de.oszimt.DreiSchichten.view;

import de.oszimt.DreiSchichten.controller.ViewController;
import de.oszimt.DreiSchichten.model.Mitglied;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Konstantin Görlitz
 */
public class Mitgliederliste extends javax.swing.JPanel {
    
    private ViewController viewcontroller;

    /**
     * Creates new form Mitgliederliste
     */
    public Mitgliederliste() {
        initComponents();
    }
    
    public Mitgliederliste(Mitglied[] mitgliederliste){
        this();
        setMitglieder(mitgliederliste);
    }
    
    public void setMitglieder(Mitglied[] mitgliederliste){
        DefaultTableModel model = (DefaultTableModel)jtMitgliederliste.getModel();
        for(final Mitglied mitglied : mitgliederliste){
            JButton button1 = new JButton("B");
            button1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    öffneMitglied(mitglied.getId());
                }
            });
            
            JButton button2 = new JButton("L");
            button2.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    löscheMitglied(mitglied.getId());
                }
            });
            
            
            
            Object[] row = {mitglied.getName(), viewcontroller.getBerufnamen(mitglied.getBerufIDs()).toString(), 
                button1, button2};
            model.addRow(row);
            
        }
    }
    
    public Mitgliederliste(Mitglied[] mitgliederliste, ViewController vc){
        this(mitgliederliste);
        this.viewcontroller=vc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitel = new javax.swing.JLabel();
        jbNeuesMitglied = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMitgliederliste = new javax.swing.JTable();

        jlTitel.setText("Mitliederliste");

        jbNeuesMitglied.setText("Neues Mitglied");
        jbNeuesMitglied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNeuesMitgliedActionPerformed(evt);
            }
        });

        jtMitgliederliste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Beruf", "Bearbeiten", "Löschen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtMitgliederliste);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTitel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbNeuesMitglied))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitel)
                    .addComponent(jbNeuesMitglied))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbNeuesMitgliedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNeuesMitgliedActionPerformed
        viewcontroller.changePanel("NeuesMitglied", 0);
    }//GEN-LAST:event_jbNeuesMitgliedActionPerformed

    private void öffneMitglied(int id){
        this.viewcontroller.changePanel("NeuesMitglied", id);
    }
    
    private void löscheMitglied(int id){
        this.viewcontroller.deleteMitglied(id);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbNeuesMitglied;
    private javax.swing.JLabel jlTitel;
    private javax.swing.JTable jtMitgliederliste;
    // End of variables declaration//GEN-END:variables
}
