PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

CREATE TABLE Dorf (
P_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100)
);

CREATE TABLE Mitglied (
P_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
FK_DORF_ID INTEGER REFERENCES Dorf(P_ID),
Name VARCHAR(100)
);

CREATE TABLE Lager (
P_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
FK_DORF_ID INTEGER REFERENCES Dorf(P_ID),
Name VARCHAR(100)
);

CREATE TABLE Berufstyp (
P_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100),
SK1 INTEGER,
SK2 INTEGER,
SK3 INTEGER,
SK4 INTEGER,
SK5 INTEGER
);

CREATE TABLE Ressource (
P_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100),
Gewicht DOUBLE,
Preis DOUBLE
);

CREATE TABLE Beruf (
P_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
FK_TYP_ID INTEGER REFERENCES Berufstyp(P_ID),
FK_Mitglied_ID INTEGER REFERENCES Mitglied(P_ID),
Punkte INTEGER
);

CREATE TABLE LagerBestand (
P_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
FK_Res_ID INTEGER REFERENCES Ressource(P_ID),
FK_Lager_ID INTEGER REFERENCES Lager(P_ID),
Menge INTEGER
);
COMMIT;
